/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import irrgarten.Directions;

/**
 *
 * @author aulas
 */
public class Cursors extends javax.swing.JDialog {

    Directions direction;

    public Directions getDirection() {
        this.setVisible(true);
        return direction;
    }

    public void setDirection(Directions direction) {
        this.direction = direction;
    }
    
    /**
     * Creates new form Cursors
     */
    public Cursors(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ARRIBA = new javax.swing.JButton();
        IZQUIERDA = new javax.swing.JButton();
        DERECHA = new javax.swing.JButton();
        ABAJO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ARRIBA.setText("ARRIBA");
        ARRIBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ARRIBAActionPerformed(evt);
            }
        });

        IZQUIERDA.setText("IZQUIERDA");
        IZQUIERDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IZQUIERDAActionPerformed(evt);
            }
        });

        DERECHA.setText("DERECHA");
        DERECHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DERECHAActionPerformed(evt);
            }
        });

        ABAJO.setText("ABAJO");
        ABAJO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABAJOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(ARRIBA))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(IZQUIERDA)
                        .addGap(74, 74, 74)
                        .addComponent(DERECHA))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(ABAJO)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ARRIBA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IZQUIERDA)
                    .addComponent(DERECHA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ABAJO)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ARRIBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARRIBAActionPerformed

       this.setDirection(Directions.UP);
       this.dispose();
    }//GEN-LAST:event_ARRIBAActionPerformed

    private void IZQUIERDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IZQUIERDAActionPerformed
        this.setDirection(Directions.LEFT);
        this.dispose();
    }//GEN-LAST:event_IZQUIERDAActionPerformed

    private void DERECHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DERECHAActionPerformed
        this.setDirection(Directions.RIGHT);
        this.dispose();
    }//GEN-LAST:event_DERECHAActionPerformed

    private void ABAJOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABAJOActionPerformed
        this.setDirection(Directions.DOWN);
        this.dispose();
    }//GEN-LAST:event_ABAJOActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABAJO;
    private javax.swing.JButton ARRIBA;
    private javax.swing.JButton DERECHA;
    private javax.swing.JButton IZQUIERDA;
    // End of variables declaration//GEN-END:variables
}
